[package]
name = "visualize"
version = "0.1.0"
authors = ["Tim Hagemann <tim@eternalwings.de>"]
edition = "2018"

[dependencies]
netcdf = { version = "0.6.1", path = "../netcdf-rust", features = ["static", "memory"] }
lazy_static = "*"